CREATE TABLE ACCOMPLICES (
       RobberId INT NOT NULL,
       BankName CHAR(50) NOT NULL,
       City CHAR(50) NOT NULL,
       RobberyDate DATE NOT NULL,
       Share DECIMAL(15,2) NOT NULL CONSTRAINT atleastzero CHECK (Share >= 0),
       CONSTRAINT apk PRIMARY KEY (RobberId, BankName, City, RobberyDate),
       CONSTRAINT arifk FOREIGN KEY (RobberId) REFERENCES ROBBERS (RobberId) ON UPDATE CASCADE ON DELETE RESTRICT,
       CONSTRAINT abncfk FOREIGN KEY (BankName, City) REFERENCES BANKS (BankName, City) ON UPDATE CASCADE ON DELETE RESTRICT,
       CONSTRAINT ardfk FOREIGN KEY (BankName, City, RobberyDate) REFERENCES ROBBERIES (BankName, City, Date) ON UPDATE CASCADE ON DELETE RESTRICT
);